### ISSUE TITLE
Replacer sometimes dies

### ISSUE THREAD

**Issue by t3chguy** [t3chguy/Limnoria-Plugins#2]
anything
sC^aC^C^11
yields

```
ERROR 2015-05-24T11:19:59 Uncaught exception in _callRegexp:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/supybot/callbacks.py", line 1465, in _callRegexp
    method(irc, msg, m)
  File "/var/lib/limnoria/Cortana/plugins/Replacer/plugin.py", line 107, in replacer
    (pattern, replacement, count) = self._unpack_sed(msg.args[1])
  File "/var/lib/limnoria/Cortana/plugins/Replacer/plugin.py", line 63, in _unpack_sed
    raise ValueError('invalid expression')
ValueError: invalid expression
ERROR 2015-05-24T11:19:59 Exception id: 0x5d2c4
ERROR 2015-05-24T11:20:29 Uncaught exception in _callRegexp:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/supybot/callbacks.py", line 1465, in _callRegexp
    method(irc, msg, m)
  File "/var/lib/limnoria/Cortana/plugins/Replacer/plugin.py", line 107, in replacer
    (pattern, replacement, count) = self._unpack_sed(msg.args[1])
  File "/var/lib/limnoria/Cortana/plugins/Replacer/plugin.py", line 63, in _unpack_sed
    raise ValueError('invalid expression')
ValueError: invalid expression
ERROR 2015-05-24T11:20:29 Exception id: 0x5d2c4
ERROR 2015-05-24T11:23:28 Uncaught exception in _callRegexp:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/supybot/callbacks.py", line 1465, in _callRegexp
    method(irc, msg, m)
  File "/var/lib/limnoria/Cortana/plugins/Replacer/plugin.py", line 107, in replacer
    (pattern, replacement, count) = self._unpack_sed(msg.args[1])
  File "/var/lib/limnoria/Cortana/plugins/Replacer/plugin.py", line 63, in _unpack_sed
    raise ValueError('invalid expression')
ValueError: invalid expression
ERROR 2015-05-24T11:23:28 Exception id: 0x5d2c4
```

**Comment by t3chguy** [comment]
Resolved.
